apiVersion: v1
kind: deployment
metadata:
  name: project-deployment
  labels:
    app: website
spec:
  replicas: 4
  selector:
    matchlabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: rahuldeswalone/websiteimage
        ports:
        - containerPort: 80
