apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: webiste
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webiste
  template:
    metadata:
      labels:
        app: webiste
    spec:
      containers:
      - name: webiste
        image: rahuldeswalone/webisteimage
        ports:
        - containerPort: 80
